name = "playjonny-app-com-es"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=playjonny-app.com.es"
HMAC_KEY = "0fe573f8361546333896a2f2116d90d70f58d1b9ca5fc76e4073b254c29c7884"
COOKIE_NAME = "ssu"
PLAY_PATH = "start-now"
BUTTON_ID = "pff91c10c6f6e791087e7eeb74567a99f"
GATE_SALT = "6fb7b7efb318f92a"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "1gbk"
CTA_SELECTOR = ".play-button"
